### ISSUE TITLE
Repeated sampling

### ISSUE THREAD

**Issue by thompsonsed** [sahilm89/lhsmdu#1]
Hi Sahil,

I am using your (extremely useful) script for sampling from parameter space, but this needs to be done identically on repeated simulations. I noticed that supplying `randomSeed` to `sample()` has no effect, so have modified my version to have `randomSeed = None` by default, and include 

`if randomSeed is not None:
        random.seed(randomSeed)`

within `sample()`

This solved my issue. Reporting here in case it should be included into the main commit.

Apologies if this is the wrong place to log this issue; I'm new to github.

Thanks,

Sam

**Comment by sahilm89** [comment]
Hi Thompson,

randomSeed should now work, thanks!
