### ISSUE TITLE
lhsmdu to work with scipy distributions (and ranges)

### ISSUE THREAD

**Issue by MatthiVH** [sahilm89/lhsmdu#6]
Hi there,

When creating samples with lhsmdu, is there a way to do it not uniformly but according to some/all of the scipy distributions (e.g., normal, alpha, beta, lognormal, ... about 100 different distributions are in scipy). 

Ideally would be to have something that sets the distribution and range for each of the variables, then an amount of samples which is obviously equal for all variables and to do latin-hypercube or MC based on that. I'm just thinking out loud by the way as someone who uses it to do simulation analyses (not as a programmer).

Kind regards

**Comment by sahilm89** [comment]
@MatthiVH Hi, please check the README for sampling from arbitrary CDFs. I've put up an example (with a Gaussian) there that shows exactly this. Essentially, the idea is to use the uniformly sampled n-dimensions returned by the lhsmdu and using that to sample from CDF for the distribution of interest. The function inverseTransformSample should do it for you. Let me know if you face any trouble with it.
Best,
Sahil

**Comment by MatthiVH** [comment]
Hi Sahil,

Yes, this works, some example info or scripts on how to use the code for often used applications of it is always handy for new visitors of the package (or new lhs/mc users like me a month ago). But this seems to be there now, so that's really helpful! Thanks!

Kind regards,
Matthias

**Comment by sahilm89** [comment]
Closing this issue.
